name: hello-world
on:
  push:
    branches: ["stages"]

env: 
  TEXT: "Edwin"

jobs:
  prints:
    runs-on: ubuntu-latest

    steps:
      - name: print-to-screen
        run: echo "hello world!! ${{ env.TEXT }}"

      - name: print-to-screen
        run: echo "secretvalue!! ${{ secrets.SECRET_NAME }}"