name: STAGE
on:
  push:
    branches: ["stage"]


env: 
  REGISTRY: cache
  IMAGE_NAME: kubelabs_publicapi
  OPS_REPO: Edmoralesc/Dev
  OPS_BRANCH: main

  # emoralesc/kubelabs_publicapi

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
        with: 
          fetch-depths: 0
      - name: Login to Docker
        uses: docker/login_action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build & push
        uses: docker/build-push-actions@v1
        with:
          push: true  
          tags: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV=${{ secret.APP_ENV }}


